@startuml
'https://plantuml.com/class-diagram
left to right direction

object Customer
object Admin
object User
object Bom
object Product
object Request
object Carport
object Shed
object ProductionLine

User : String username
User : String password
User : String role

Customer : String name
Customer : int zipCode
Customer : String city
Customer : String phoneNumber
Customer : String email

Request : boolean isAccepted
Request : boolean isPaid

Carport : double height
Carport : double length
Carport : double width
Carport : String roofMaterial
Carport : String roofShape
Carport : int roofAngle

Shed : double length
Shed : double width
Shed : String floorMaterial

Bom : double totalPrice
Bom : String description
Bom : String svgDrawing

ProductionLine : int amount
ProductionLine : double totalProductPrice



Product : String name
Product : String category
Product : String unit
Product : String productType
Product : double height
Product : double width
Product : double pricePrMeasurment
Product : int amount


Carport o-- Shed
User <|-- Admin
User <|-- Customer
Request o-- Bom
Bom o-- ProductionLine
ProductionLine o-- Product
Customer o-- Request
Admin --- Request
Request o-- Carport

@enduml